#!/bin/bash
# Block edits to specs/ unless the current branch was created by create-new-feature.sh.
# Enforces the kiln branch naming convention: ###-name or YYYYMMDD-HHMMSS-name.
# This prevents manual branch creation (e.g., feature/my-thing) which breaks
# script path resolution and causes cascading failures in the pipeline.

set -euo pipefail

INPUT=$(cat)
TOOL_NAME=$(echo "$INPUT" | jq -r '.tool_name // empty' 2>/dev/null)
FILE_PATH=$(echo "$INPUT" | jq -r '.tool_input.file_path // empty' 2>/dev/null)

# Only check Edit and Write tools
if [[ "$TOOL_NAME" != "Edit" && "$TOOL_NAME" != "Write" ]]; then
  exit 0
fi

# If no file path, allow
if [[ -z "$FILE_PATH" ]]; then
  exit 0
fi

# Only enforce on specs/ directory edits
case "$FILE_PATH" in
  */specs/*)
    ;;
  *)
    exit 0
    ;;
esac

# Allow if not in a git repo
PROJECT_DIR="${CLAUDE_PROJECT_DIR:-.}"
if ! git -C "$PROJECT_DIR" rev-parse --is-inside-work-tree >/dev/null 2>&1; then
  exit 0
fi

# Allow edits on main/master (e.g., merging PRs)
BRANCH=$(git -C "$PROJECT_DIR" rev-parse --abbrev-ref HEAD 2>/dev/null || echo "")
if [[ "$BRANCH" == "main" || "$BRANCH" == "master" ]]; then
  exit 0
fi

# Check if SPECIFY_FEATURE env var is set (set by create-new-feature.sh)
if [[ -n "${SPECIFY_FEATURE:-}" ]]; then
  BRANCH="$SPECIFY_FEATURE"
fi

# Enforce naming convention: ###-name or YYYYMMDD-HHMMSS-name
if [[ "$BRANCH" =~ ^[0-9]{3}- ]] || [[ "$BRANCH" =~ ^[0-9]{8}-[0-9]{6}- ]]; then
  exit 0
fi

cat >&2 <<EOF
BLOCKED: Branch "$BRANCH" does not follow the kiln naming convention.

Feature branches must be named like:
  001-feature-name       (sequential)
  20260319-143022-name   (timestamp)

These names are generated by create-new-feature.sh, which runs automatically
when you use /specify. Do not create feature branches manually.

To fix: switch to main and run /specify to start your feature properly.
EOF
exit 2
